### ISSUE TITLE
Encourage inclusion of rate limit information 

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#165]
- [ ] Census
- [ ] Federal Communications Commission
- [x] Food and Drug Administration [[here](https://open.fda.gov/api/reference/#authentication)]
- [x] General Services Administration - Auctions [[here](http://gsa.github.io/auctions_api/basics)]
- [ ] General Services Administration - Data.gov [[waiting](https://github.com/GSA/data.gov/issues/561) for them to migrate endpoints]
- [x] General Services Administration - SAM [[here](http://gsa.github.io/sam_api/sam/basics.html)]
- [x] General Services Administration - FBOpen [[here](http://18f.github.io/fbopen/apidocs/)]
- [ ] National Renewable Energy Laboratory [[waiting](https://github.com/NREL/developer.nrel.gov/issues/14) for them to migrate endpoints]
- [x] National Institutes of Health - 3D Printing API [[here](http://niaid.github.io/3dpx_api/use_api/#rate-limits)]
- [x] Regulations.gov API [[here](http://regulationsgov.github.io/developers/basics.html#rate-limits)]
- [ ] U.S. Department of Agriculture - ERS [[suggested](https://github.com/USDA/USDA-APIs/issues/37)]
- [ ] U.S. Department of Agriculture - National Nutrient Database [[suggested](https://github.com/USDA/USDA-APIs/issues/37)]

**Comment by gbinal** [comment]
Agencies have generally been doing this but we also haven't found more need to engage with them on it, so I'm going to go ahead and close this one.
