### ISSUE TITLE
Track todo list of where we want to be 

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#578]
Taking a page from the thought experiment, 'what if we all were hit by different buses, how would we leave the program', items to get to:
* [ ] remap what spreadsheets I want to manage, and use the admin API to power them
* [ ] tidy up the google drive folder 
* [ ] catch up on dependabot 
* [ ] migrate to federalist 
* [ ] plug the customer service holes 
* [ ] template emails and make a chain of  communications 
* [ ] prune issue tracker
* [ ] create a program management repo (using the wiki for now)
* [ ] consider spinning off the website into another repo
* [ ] what else?

_Tracking notes [here](https://docs.google.com/document/d/1upYL8922medUojxPoPqiptfFZBu8qZ4yptImVgIG_WA/edit#heading=h.vp26ytgn4hgy)_

**Comment by gbinal** [comment]
did this but forgot to close it at the time
